name: build-and-push

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # This step checks out the code from the repository
      - name: Checkout
        uses: actions/checkout@v3

        # This step logs in to Docker Hub using the provided credentials in Github Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # This step sets up Buildx, which is a tool that allows building and pushing multi-architecture images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # This step builds the Docker image and pushes it to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          # The tag of the image, including the repository and image name
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-server:latest
          # Platforms to build the image for
          platforms: linux/amd64,linux/arm64,linux/arm/v7
